name: testx
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/leisim/testx

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dartx: ^0.2.0
    
dev_dependencies:
  flutter_test:
    sdk: flutter